### ISSUE TITLE
Overriding the SAML user details service bean

### ISSUE THREAD

**Issue by budjb** [jeffwils/grails-spring-security-saml#11]
We're trying to integrate this plugin with our SAML service, and we would like to override the SAML user details service bean. Since this name conflicts with a bean of the same name, which is used by Spring Security, I'm not quite sure how to define our own bean instead of using the one bundled with the plugin. We could modify the plugin source, but I'd rather see if it's supported out of the box. How do we define our own implementation of this bean?

**Comment by jeffwils** [comment]
Add your own class in your grails project that incorporates all the functionality you want (your custom, the SAML Plugin, etc) and configure that class to the userDetails bean in resources.groovy.  That will override what is in the plugin initialization.

**Comment by irstevenson** [comment]
Looks like all sorted (nothing for 9 days). If further guidance needed, can re-open - just ask here.
