### ISSUE TITLE
HTTPMetadataProvider support

### ISSUE THREAD

**Issue by valentingoebel** [jeffwils/grails-spring-security-saml#17]
Could we perhaps detect if the path to the provider begins with "https:" and then automatically use the HTTPMetadataProvider instead of FilesystemMetadataProvider?

https://docs.spring.io/spring-security-saml/docs/1.0.x/reference/html/chapter-quick-start.html#quick-start-idp-metadata

On top of this change we will also need a new configuration value for the timeout setting.

**Comment by irstevenson** [comment]
I also would like to see this, as I was reading the config code the other day and see there was even a comment place holder for it. Be good to support both HTTP and HTTPS.

**Comment by irstevenson** [comment]
I see @valentingoebel has an active branch for this, so will assign.

**Comment by irstevenson** [comment]
All merged into `develop`.
