### ISSUE TITLE
GORM 5 incompatibility

### ISSUE THREAD

**Issue by parizpe1** [jeffwils/grails-spring-security-saml#2]
took an empty grails 3.2.8 app, ran and compiled it (successfully), then, put the exact same build gradle as in the README, ran s2-quickstart (also succesfully) and encountered the same issue as @mburak.

The test.TestRole is a conflict with the static constraints, but even after overriding the TestRole class, the GormEntity error prevails:

| Running application...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileGroovy'.
> org/grails/datastore/gorm/GormEntity$Trait$FieldHelper

grails doc reports the same issue here (GORM 5 Upgrade)

http://docs.grails.org/3.1.0.RC1/guide/single.html#upgrading3x

Stacktrace attached
[stacktrace.txt](https://github.com/jeffwils/grails-spring-security-saml/files/890365/stacktrace.txt)

**Comment by jeffwils** [comment]
Thank you.  I will recompile the plugin and get an additional version out there for 3.1+

**Comment by parizpe1** [comment]
Thank you for the very prompt reply.
Just for the (mostly personal) record, the latest grails doc also documents this issue.
http://docs.grails.org/3.2.8/guide/single.html#upgrading3x

**Comment by jeffwils** [comment]
Version 3.1.0 of the plugin has been released.  It resolves the GORM incompatibility issues as well.  If your grails app uses version 3.0.x then use version 3.0.0 of the plugin.  If your grails app is 3.1+ then use the 3.1.0 version of the plugin.
