### ISSUE TITLE
The plugin id 'spring-boot' is deprecated

### ISSUE THREAD

**Issue by irstevenson** [jeffwils/grails-spring-security-saml#21]
As part of the upgrade to Grails 3.3.x we should probably address this minor item in `build.gradle` causing this warning:

```
$ ./gradlew build
The plugin id 'spring-boot' is deprecated. Please use 'org.springframework.boot' instead.
```

**Comment by valentingoebel** [comment]
Because this is such a minor change I've included it as part of https://github.com/jeffwils/grails-spring-security-saml/pull/20.
