### ISSUE TITLE
spring-security-saml compatible plugin for Grails-3.3.2 not available

### ISSUE THREAD

**Issue by ravikovour** [jeffwils/grails-spring-security-saml#23]
We are using Grails-3.3.2. I want to get corresponding spring-security-saml plugin.
From the document it says : For Grails 3.3.x - Use Version 3.3.x of the plugin. 
But it is not available in git repo. While building my app
it gives error Could not find org.grails.plugins:spring-security-saml:3.3.0
provide a release of saml plugin compatible with Grails-3.3.2 (3.3.x) ASAP.

**Comment by irstevenson** [comment]
Hi @ravikovour ,

We've just finished the updates for 3.3.x, and are now ready to realise. Keep watching. ;)

@jeffwils ,

AFAIK you're the only one with the bintray credentials for the plugin. `master` now works with 3.3.x, so would you be able to release? Or do you need us first to organise a `3.3.0` branch?

(After that, we can start looking at further work for the 3.3.1 version.)

**Comment by valentingoebel** [comment]
This project doesn't appear to use tags so creating a new branch per release is probably the current workflow.

**Comment by valentingoebel** [comment]
I have created the '3.3.0' branch.

https://github.com/jeffwils/grails-spring-security-saml/tree/3.3.0

**Comment by jeffwils** [comment]
Its published.  Great work by the both of you.....I have been wanting to do this for a while, just have not had the bandwidth to get it done.  I will look at how I can add you for bintray publishing....(currently do not have premium and can't add a team)
