### ISSUE TITLE
What is the git workflow for this repo?

### ISSUE THREAD

**Issue by irstevenson** [jeffwils/grails-spring-security-saml#26]
Heya @jeffwils ,

Just attempting to work on a couple of items towards 3.3.1, however I'm a bit lost as to where to put them within the workflow for this repo.

At first glance, it would appear that there is a branch for each minor release, but sometimes these are crossing over (see `3.1.1`, `3.0.1` and `3.1.2`). I was (previously) thinking that `master` was used to work towards all new releases, however I notice that some fixes have not been merged back. (Indeed, I note that in the release we've just done we're actually missing a few fixes - such as the active flag fix, and the 'Fixed providers and userGroupToRoleMappings to accept a list of maps.  Fixed defaultIdp'.)

**So could you advise what you'd like to see done?**

Or if you don't have too strong a preference, maybe we use gitflow?

Whatever is decided, I plan to then capture that in a `CONTRIBUTING.md` to make it easy going forward. 😉👍 And following that, we can look at making sure we get the bits that were not in 3.3.0 back in.

Cheers!

**Comment by jeffwils** [comment]
This was due to gorm incompatibilities.  The versions of the plugin follow the grails versioning pattern.  The plugin with 3.0.x can be used with grails 3.0.x.  Plugin 3.1.x with grails 3.1.x etc.  Since they each had to be compiled against a different version of Gorm, and any bugs that needed fixed needed fixed in both 3.0.x and 3.1.x.  The issue was I couldn't make the 3.1 plugin backward compatible for grails 3.0.x.

I have no problem using gitflow at all.  

Thanks again for all of the major effort on this project

**Comment by irstevenson** [comment]
Thanks @jeffwils , not a problem. I'll work towards moving the project to gitflow and documenting as mentioned above.

P.S. Sorry for slow reply, had a hectic easter break.

**Comment by irstevenson** [comment]
Heya @jeffwils ,

So I've created a `develop` branch and placed a rough [CONTRIBUTING.md](https://github.com/jeffwils/grails-spring-security-saml/blob/develop/CONTRIBUTING.md) in it.

If you could cast your eye over it, and let us know if it's okay that'd be great. Once you're happy, I'll then close off this ticket and make sure we're working along those lines. (And first and foremost, I can start bring forward some of those other fixes.)

Cheers.

**Comment by irstevenson** [comment]
Alright, I'm going to declare this pretty  much in place. Just thrown the above PR up for a quick glance before we merge to master. But otherwise, I'm going to close this off and start merging other missing bits into develop. ;)
