### ISSUE TITLE
Active flag has no affect

### ISSUE THREAD

**Issue by irstevenson** [jeffwils/grails-spring-security-saml#33]
...however there has been a fix in the past, so we just need to add it back onto `develop` branch, test and be done.

See lines 79-84 of SpringSecuritySamlGrailsPlugin.groovy:

https://github.com/jeffwils/grails-spring-security-saml/blob/f54a8afe99adbac7ac886d7d58ede68110193323/src/main/groovy/org/grails/plugin/springsecurity/saml/SpringSecuritySamlGrailsPlugin.groovy#L79-L84

These should probably all be updated as per:

https://github.com/jeffwils/grails-spring-security-saml/commit/fd0150cd2ced1b7482e7907be46a2f21eb024e20#diff-040c2cc982d97779d0f006aef5310bfb

**Comment by valentingoebel** [comment]
Now that this is out of the way I'll close the issue.
