### ISSUE TITLE
Assign roles based on database ONLY

### ISSUE THREAD

**Issue by irstevenson** [jeffwils/grails-spring-security-saml#43]
Currently, the plugin **only** does role assignment based on an attribute passed back in the SAML AuthResponse and configured via `userGroupAttribute` and `userGroupToRoleMapping`. However, there are cases where roles assigned to a user should simply be based on those already configured in the applications security domain classes (i.e. UserRole and Role equivalents).

This supports cases where perhaps the IDP only ever returns the Principal; and/or where the Application Owners are unable to configure group memberships etc in the IDP (or it's backing identity store).

Implementation should consist of:

1. A new config value: `saml.useLocalRoles`
2. A condition in the `SpringSamlUserDetailsService` in the `getAuthoritiesForUser` method where if this flag is `true` it simply gets the authorities via a call to `getAuthorities()` on the user object for supplied `username` and returns them appropriately as `SimpleGrantedAuthority`s.

**Comment by valentingoebel** [comment]
The PR was merged successfully.
