### ISSUE TITLE
Inform user about potential name conflicts

### ISSUE THREAD

**Issue by valentingoebel** [jeffwils/grails-spring-security-saml#45]
```
$> grails s2-quickstart com.jeffwils User Role
```

The table name "user" conflicts with the keyword "USER" in postgres and potentially other RDBMS.
One workaround is to use a non conflicting table name.
```
   static mapping = {
        table 'users'
    }
```

**Comment by irstevenson** [comment]
Tricky one that isn't it, as it's really a Spring Security Core plugin concern, however we will have users who are using this plugin as their primary interface and it's nice to be helpful. I note that Core uses primarily the same example: https://grails-plugins.github.io/grails-spring-security-core/3.2.x/index.html#s2-quickstart

But they also provide one different example with along the lines of:

    grails s2-quickstart com.yourapp Person Authority

I'd be inclined to say we should both change the command in our doco to read:

    $> grails s2-quickstart com.yourapp UserAcct Role

So if people just grab the command it'll work on a higher number of DBs. Plus add a note as you mention around conflicts and how to further customise via a mapping.
