### ISSUE TITLE
Correct documentation for the use of `defaultIdp`

### ISSUE THREAD

**Issue by irstevenson** [jeffwils/grails-spring-security-saml#48]
Currently the documentation in README.md (moving to index.md in #46) has incorrect information for the usage of `saml.metadata.defaultIdp`. It needs to be explicit that `defaultIdp` should be the EntityId URI - **not** one of the names in the providers Map. (See discussion in at https://github.com/jeffwils/grails-spring-security-saml/issues/34#issuecomment-396524285.)

Note also, in updating the table for configuration params and values that the configuration examples in the same file also need updating. But when looking for them, be careful as they currently have a typo where `defaultIdp` is actually put as `defaultldp` (note the capital i has been replaced with a lower case l) - so search carefully. :wink:

**Comment by irstevenson** [comment]
We still need to update the examples, as we only updated the table in #50.

**Comment by valentingoebel** [comment]
I have updated the examples in this PR: #54

**Comment by valentingoebel** [comment]
Merged.
