### ISSUE TITLE
defaultFailureUrl should be configurable

### ISSUE THREAD

**Issue by jnunderwood** [jeffwils/grails-spring-security-saml#52]
The method `authenticationFailureHandler()` in the file `SpringSecuritySamlGrailsPlugin.groovy` has a hard-coded value for `defaultFailureUrl`. It references a `log4J` controller(?) that does not exist in the project, causing login failures to further fail in an unexpected way. It should have a more reasonable default value, such as `conf.failureHandler.defaultFailureUrl`.

```
SpringSecuritySamlGrailsPlugin.groovy:

authenticationFailureHandler(AjaxAwareAuthenticationFailureHandler) {
    redirectStrategy = ref('redirectStrategy')
    defaultFailureUrl = '/log4J/logging' //conf.failureHandler.defaultFailureUrl //'/login/authfail?login_error=1'
    useForward = conf.failureHandler.useForward // false
    ajaxAuthenticationFailureUrl = conf.failureHandler.ajaxAuthFailUrl // '/login/authfail?ajax=true'
    exceptionMappings = conf.failureHandler.exceptionMappings // [:]
}
```

**Comment by valentingoebel** [comment]
This change has already been merged in the past into the develop branch (See [SpringSecuritySamlGrailsPlugin.groovy](https://github.com/jeffwils/grails-spring-security-saml/blob/develop/src/main/groovy/org/grails/plugin/springsecurity/saml/SpringSecuritySamlGrailsPlugin.groovy#L304)) and will be available in the next release.

**Comment by irstevenson** [comment]
Noting @jnunderwood 's thumbs up and that it's planned for next release (hopefully soon), so closing ticket.
