### ISSUE TITLE
Grails 4 release?

### ISSUE THREAD

**Issue by runger1101001** [jeffwils/grails-spring-security-saml#61]
Hi,

Are there any plans for a grails 4 release of this plugin? We'd need one...

What would be involved, is it a big job?

Thanks and regards from Vienna,

Richard

**Comment by valentingoebel** [comment]
I'm working on it. It doesn't look like a big job. So far I didn't run into any issues after updating spring security core to version 4. If everything goes well, it will take a few days.

**Comment by valentingoebel** [comment]
I have created a new branch '4.0.0' with the latest changes to support Grails 4. You can install it by cloning the repository and using the `grails install` command. I will publish the release on bintray later.

**Comment by runger1101001** [comment]
Thank you so much, that is wonderful! We will test it out and let you know if it works as expected...

**Comment by valentingoebel** [comment]
Now that I have upgraded one of my applications to grails 4 and therefore tested grails-spring-security-saml on a real application I will publish the 4.0.0 release.

**Comment by valentingoebel** [comment]
Version 4.0.0 is now available on the official grails repository: http://plugins.grails.org/plugin/valentingoebel/spring-security-saml
