### ISSUE TITLE
Issue in 3.3.x while configuring IDP alias containing dot or url configuration in application.groovy

### ISSUE THREAD

**Issue by vsachinv** [jeffwils/grails-spring-security-saml#67]
Hi,

We are facing challenge with the plugin code of 3.3.1 when idp alias is configured with value containing dot or url e.g. if we give configuration like below.
`grails.plugin.springsecurity.saml.metadata.providers = ["https://xyz.windows.net/12323-2334-234": "client_idp.xml"]`

then Grails config ConfigSlurper breaks even 'https://xyz', 'windows' as config keys and then below code throws exception and doesn't let application startup due iterating over keys like 'https://xyz' along with key 'https://xyz.windows.net/12323-2334-234'. 
`2020-06-26 21:15:29,422 - M: APPServer ERROR  org.springframework.boot.SpringApplication - Application startup failed
groovy.lang.MissingMethodException: No signature of method: org.grails.config.NavigableMap.startsWith() is applicable for argument types: (java.lang.String) values: [https:]
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:71)
    at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:53)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
    at java_lang_String$startsWith$2.call(Unknown Source)
    at org.grails.plugin.springsecurity.saml.SpringSecuritySamlGrailsPlugin$_doWithSpring_closure1$_closure7$_closure21.doCall(SpringSecuritySamlGrailsPlugin.groovy:153)`

Below code is there in SpringSecuritySamlGrailsPlugin.groovy file.

`conf.saml.metadata.providers.each {k,v ->`

To overcome this short coming code should be like below:
`conf.saml.metadata.providers.toFlatConfig().each {k,v ->`

**toFlatConfig()** can help to avoid such situations. Just, we need to make sure to safe it from null config.

It was working in earlier version because in that providers were list of maps and accordingly code was there in SpringSecuritySamlGrailsPlugin.groovy file.

**Comment by valentingoebel** [comment]
I don't think the key value is used anymore in 3.3.1. You can set it to any arbitrary value because it was meant to be an alias that could be used for defaultIdp but nowadays you just enter the entire entityID in defaultIdp.

You can replace the dots with a placeholder. ( . -> _ )
```
grails.plugin.springsecurity.saml.metadata.providers = ["https://xyz_windows_net/12323-2334-234": "client_idp.xml"]
```

**Comment by vsachinv** [comment]
@valentingoebel if thats the case, then its just breaking what was configured back with Grails 3.2.9 thats it nothing else would be an issue. I guess, I got the point. Thanks for the support. You can close this issue. Only the thing worth mentioning here is that, alias name can't contain dot's :) and use of defaultIdp property.
